potentia_backend/loginSignup/urls.py
# loginSignup/urls.py
from django.conf.urls import url
from loginSignup import views
# SET THE NAMESPACE!
app_name = 'loginSignup'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

potentia_backend/post/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = "post"

urlpatterns = [
    url(r'addtrans/', views.add_transaction, name="Add_Trans"),
    url(r'MyTrans/',views.my_trans, name="My_Trans"),
    url(r'AvailTrans/',views.open_trans.as_view(), name="Open_Trans"),
    url(r'CompTrans/', views.make_trans, name="Make_Trans"),

]

potentia_backend/potentia_backend/urls.py
# dprojx/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from loginSignup import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^special/', views.special, name='special'),
    url(r'^loginSignup/', include('loginSignup.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'post/', include('post.urls'))
]

potentia_backend/loginSignup/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver



class AddSignup(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='additional')
    address = models.CharField(max_length = 100)
    phone = models.IntegerField()
    renewable_source = models.CharField(max_length = 100)
    Potentia = models.IntegerField(default=0)
    flares = models.IntegerField(default=0)

#
# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         AddSignup.objects.create(user=instance)
#
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

potentia_backend/loginSignup/forms.py
from django import forms
from django.contrib.auth.models import User

from loginSignup.models import AddSignup


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'password', 'email')

class AddSignupForm(forms.ModelForm):
    class Meta:
        model = AddSignup
        fields = ('address', 'phone', 'renewable_source')

potentia_backend/loginSignup/views.py
from django.shortcuts import render, redirect
from loginSignup.forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import AddSignupForm


def index(request):
    return render(request, 'loginSignup/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        add_form = AddSignupForm(data = request.POST)
        if user_form.is_valid() and add_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            adf = add_form.save(commit=False)
            adf.user = user
            adf.save()
            registered = True
            login(request, user)
            return redirect('index')
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
        add_form = AddSignupForm()
    return render(request, 'loginSignup/registration.html',
                  {'user_form': user_form, 'add_form': add_form,
                           'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(
                username, password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'loginSignup/login.html', {})

potentia_backend/templates/loginSignup/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Energion</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">Energion</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'loginSignup:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'loginSignup:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

potentia_backend/templates/loginSignup/index.html
{% extends "loginSignup/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Energion</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
        <a href="{% url 'post:My_Trans' %}"><button>My Transactions</button></a>
        <a href="{% url 'post:Add_Trans' %}"><button>Add a New Transaction</button></a>
        <a href="{% url 'post:Open_Trans' %}"><button>View Open Transactions</button></a>
    {% else %}
        <h2>An energy trading platform for a better world...</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

potentia_backend/templates/loginSignup/login.html
{% extends 'loginSignup/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'loginSignup:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

potentia_backend/templates/loginSignup/registration.html
{% extends "loginSignup/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ add_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}