potentia_backend/post/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = "post"

urlpatterns = [
    url(r'addtrans/', views.add_transaction, name="Add_Trans"),
    url(r'MyTrans/',views.my_trans, name="My_Trans"),
    url(r'AvailTrans/',views.open_trans.as_view(), name="Open_Trans"),
    url(r'CompTrans/', views.make_trans, name="Make_Trans"),

]

potentia_backend/potentia_backend/urls.py
# dprojx/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from loginSignup import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^special/', views.special, name='special'),
    url(r'^loginSignup/', include('loginSignup.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'post/', include('post.urls'))
]

potentia_backend/post/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Transactions(models.Model):
    trans_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    tosenduser = models.ForeignKey(User, on_delete=models.CASCADE, related_name="tosenduser", null=True)
    amount = models.IntegerField()
    cost = models.IntegerField()
    sent_transfer_tx = models.TextField(null=True)
    sent_creation_tx = models.TextField(null=True)
    status = models.BooleanField(default=False)

potentia_backend/post/forms.py
from django import forms
from django.contrib.auth.models import User

from post.models import Transactions


class AddTransactionForm(forms.ModelForm):
    class Meta:
        model = Transactions
        fields = ('amount',)

potentia_backend/post/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic import ListView

from loginSignup.models import AddSignup
from .block_init import *
from post.forms import AddTransactionForm
from post.models import Transactions
from bigchaindb_driver import BigchainDB
from bigchaindb_driver.crypto import generate_keypair
from django.db.models import Q
#rated constants 
rate = 8
sender, reciever = generate_keypair(), generate_keypair()


def trasact_block(sender, reciever, flares):
    sender_key, reciever_key = generate_keypair(), generate_keypair()

    # Use YOUR BigchainDB Root URL here
    bdb_root_url = 'https://test.bigchaindb.com/'

    bdb = BigchainDB(bdb_root_url)

    energy = {
        'data': {
            'flares': {
                # sameeran replace timestamp, public key sender dictionaties with real values from views
                'timestamp': 'timestamp',
                # they are not supposed to be string but variables.
                'public_key_sender': sender_key.public_key,
                'sender': sender,
                'public_key_reciever': reciever_key.public_key,
                'flares': flares
            }
        }
    }

    prepared_creation_tx = bdb.transactions.prepare(
        operation='CREATE',
        signers=sender_key.public_key,
        asset=energy
    )

    fulfilled_creation_tx = bdb.transactions.fulfill(
        prepared_creation_tx,
        private_keys=sender_key.private_key
    )

    sent_creation_tx = bdb.transactions.send_commit(fulfilled_creation_tx)

    txid = fulfilled_creation_tx['id']

    asset_id = txid

    transfer_asset = {
        'id': asset_id
    }

    output_index = 0
    output = fulfilled_creation_tx['outputs'][output_index]

    transfer_input = {
        'fulfillment': output['condition']['details'],
        'fulfills': {
            'output_index': output_index,
            'transaction_id': fulfilled_creation_tx['id']
        },
        'owners_before': output['public_keys']
    }

    prepared_transfer_tx = bdb.transactions.prepare(
        operation='TRANSFER',
        asset=transfer_asset,
        inputs=transfer_input,
        recipients=reciever_key.public_key,
    )

    fulfilled_transfer_tx = bdb.transactions.fulfill(
        prepared_transfer_tx,
        private_keys=sender_key.private_key,
    )

    sent_transfer_tx = bdb.transactions.send_commit(fulfilled_transfer_tx)
    q=[sent_transfer_tx, sent_creation_tx]
    return q


def add_transaction(request):
    av_flares = request.user.additional.flares
    if request.method == 'POST':
        trans_form = AddTransactionForm(data=request.POST)
        if trans_form.is_valid():
            trans = trans_form.save(commit = False)
            trans.user = request.user
            trans.cost = trans.amount * rate
            if trans.amount >= request.user.additional.flares:
                return render(request, 'post/TransUploadFail.html',{'user':request.user})
            trans.status = False
            trans.save()
            return render(request, 'post/TransUploadSuccess.html',{'user':request.user, 'trans_id':trans.trans_id})



        else:
            return HttpResponseRedirect(request, 'AllTrans')
    else:
        trans_form = AddTransactionForm()
    return render(request, 'post/AddTrans.html', {'trans_form':trans_form, 'rate':rate, 'av_flares':av_flares})


def my_trans(request):
    av_flares = request.user.additional.flares
    all_trans = Transactions.objects.filter(Q(user__exact=request.user) | Q(tosenduser__exact=request.user))
    return render(request, 'post/AllTrans.html',{'all_trans':all_trans, 'PotentiaWallet': request.user.additional.Potentia, 'av_flares':av_flares})

class open_trans(ListView):
    template_name = 'post/opentrans.html'
    context_object_name = 'OpenTrans'
    queryset = Transactions.objects.filter(status__exact=False)


def make_trans(request):
    pk = request.POST.get('pk', None)
    trans = Transactions.objects.get(trans_id__exact=pk)
    if trans.cost <= request.user.additional.Potentia:
        trans.tosenduser = request.user
        a = trasact_block(trans.user.username,trans.tosenduser.username,trans.amount)
        trans.sent_transfer_tx = a[0]
        trans.sent_creation_tx = a[1]
        trans.status = True
        request.user.additional.Potentia = request.user.additional.Potentia - trans.cost
        trans.user.additional.flares = trans.user.additional.flares - trans.amount
        trans.save()
        return render(request, 'post/TransComplete.html',{'trans':trans})
    else:
        return render(request, 'post/TransFail.html')

potentia_backend/templates/post/AddTrans.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add a New Transaction</title>
</head>
<body>
<h1>Add A New Transaction</h1>
<h4>Note: The Current Conversion Rate Is: 1 Flare = {{ rate }} Potentia </h4>
<h4>Also, 1 Flare = 1 KWH of Energy</h4>
<h4>You Currently have {{ av_flares }} Flares Available to Send</h4>
<br><br><br><br>
<form method="post" action="{% url 'post:Add_Trans' %}">
    {% csrf_token %}
    {{ trans_form.as_p }}
    <input type="submit">
</form>


</body>
</html>

potentia_backend/templates/post/AllTrans.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Your Transactions</title>
</head>
<body>
<h5><a href="{% url 'index' %}">Go Back</a> </h5>
<h1>These Are All The Transactions You Have Made</h1>
<h4>Note: The Current Conversion Rate Is: 1 Flare = {{ rate }} Potentia </h4>
<h4>Also, 1 Flare = 1 KWH of Energy</h4>
<h3>You Have {{ PotentiaWallet }} Potentia</h3>
<br><br><br><br>
<br>
<br>
<br>
{% for tra in all_trans %}
    <p>Status: {{ tra.status }}</p>
    <p>Amount: {{ tra.amount }}</p>
    <p>Cost: {{ tra.cost }}</p>
    <p>Creation TX: {{ tra.sent_creation_tx }}</p>
    <p>Transfer TX: {{ tra.sent_transfer_tx }}</p>

<br><br><br><br><br>
{% endfor %}
</body>
</html>

potentia_backend/templates/post/TransComplete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Success!</title>
</head>
<body>
<h1>The Transaction Has Been Completed Succesfully!</h1>
<h3>Here are the details:</h3>
<p>Source: {{ trans.user }}</p>
<p>Receiver: {{ trans.tosenduser }}</p>
<p>Energy Transfered: {{ trans.amount }} Flares</p>
<p>Cost: {{ trans.cost }} Potentia</p>
<p>Transfer TX: {{ trans.sent_creation_tx }}</p>
<p>Creation TX: {{ trans.sent_creation_tx }}</p>
<br><br><br><br><br>
<h3>Click the button below to go back Home</h3>
<a href="{% url 'index' %}"><button>Home</button></a>
</body>
</html>

potentia_backend/templates/post/TransFail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Oops!</title>
</head>
<body>
<h1>Oops!</h1>
<h3>It seems the you don't have enough flares to post this transaction</h3>
<h4>Click the button below to go back to Home</h4>
<a href="{% url 'index' %}"><button>Home</button></a>
</body>
</html>

potentia_backend/templates/post/TransUploadFail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Oops!</title>
</head>
<body>
<h1>Oops!</h1>
<h3>It seems the you don't have enough flares to post this transaction</h3>
<h4>Click the button below to go back to Home</h4>
<a href="{% url 'index' %}"><button>Home</button></a>
</body>
</html>

potentia_backend/templates/post/TransUploadSuccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Success!</title>
</head>
<body>
<h1>Your Transaction Has Been Posted On The Platform</h1>
<h4>Click the button below to go back to Home</h4>
<a href="{% url 'index' %}"><button>Home</button></a>
</body>
</html>

potentia_backend/templates/post/opentrans.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Available Transactions</title>
</head>
<body>
{% for OpenTran in OpenTrans %}
    <p>Source: {{ OpenTran.user.username }}</p>
    <p>Amount Of Energy: {{ OpenTran.amount }}</p>
    <p>Cost: {{ OpenTran.cost }}</p>
    <p>Transaction ID: {{ OpenTran.trans_id }}</p>
     <form method="POST" action="{% url 'post:Make_Trans' %}">
             {% csrf_token %}
            <input type="hidden" value="{{ OpenTran.trans_id }}" name="pk" />
            <input type="submit" value="Buy" />
    </form>
{#    <a href="{% url 'post:Make_Trans' OpenTran.trans_id %}"> Buy </a>#}

{% endfor %}

</body>
</html>